/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leoon_jni_SMBServerJNI */

#ifndef _Included_com_leoon_jni_SMBServerJNI
#define _Included_com_leoon_jni_SMBServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    start_smb_server
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_start_1smb_1server
  (JNIEnv *, jobject);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    stop_smb_server
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_stop_1smb_1server
  (JNIEnv *, jobject);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    set_smb_share
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_set_1smb_1share
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    set_smb_data_path
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_set_1smb_1data_1path
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    set_smb_log_level
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_set_1smb_1log_1level
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    set_smb_account
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_set_1smb_1account
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
