/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leoon_jni_SMBServerJNI */

#ifndef _Included_com_leoon_jni_SMBServerJNI
#define _Included_com_leoon_jni_SMBServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    startSMBServer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_startSMBServer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    stopSMBServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_stopSMBServer
  (JNIEnv *, jobject);

/*
 * Class:     com_leoon_jni_SMBServerJNI
 * Method:    addSMBShare
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_leoon_jni_SMBServerJNI_addSMBShare
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
